import Head from 'next/head'
import React from 'react'
import {useSelector} from 'react-redux'


export default function Home() {
  const {login} = useSelector( state => state.login)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col justify-center text-center '>
        <h1 className=''>Next Js example</h1>
        <h2>Keeping track of login state on different pages so getServerSideProps doesn't run again</h2>
        <h3>Index</h3>
        <div className='bg-gray-600 '>Login status is <p style={{color:'blue',fontSize:48}}>{login ? 'true':'false'}</p></div>

      </main>
      
    </div>
  )
}
